# Generated by Django 4.1.5 on 2023-02-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id_body', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BodyMaterial',
            fields=[
                ('id_body_material', models.AutoField(primary_key=True, serialize=False)),
                ('body_material', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id_body_type', models.AutoField(primary_key=True, serialize=False)),
                ('body_type', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neck',
            fields=[
                ('id_neck', models.AutoField(primary_key=True, serialize=False)),
                ('frets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NeckMaterial',
            fields=[
                ('id_neck_material', models.AutoField(primary_key=True, serialize=False)),
                ('neck_material', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeckType',
            fields=[
                ('id_neck_type', models.AutoField(primary_key=True, serialize=False)),
                ('neck_type', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id_producer', models.AutoField(primary_key=True, serialize=False)),
                ('producer', models.CharField(max_length=45, unique=True)),
                ('website', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=45, unique=True)),
                ('price', models.IntegerField()),
                ('id_body', models.ForeignKey(db_column='id_body', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.body')),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.category')),
                ('id_color', models.ForeignKey(db_column='id_color', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.color')),
                ('id_neck', models.ForeignKey(db_column='id_neck', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.neck')),
                ('id_producer', models.ForeignKey(db_column='id_producer', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.producer')),
            ],
        ),
        migrations.AddField(
            model_name='neck',
            name='id_neck_material',
            field=models.ForeignKey(db_column='id_neck_material', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.neckmaterial'),
        ),
        migrations.AddField(
            model_name='neck',
            name='id_neck_type',
            field=models.ForeignKey(db_column='id_neck_type', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.necktype'),
        ),
        migrations.AddField(
            model_name='body',
            name='id_body_material',
            field=models.ForeignKey(db_column='id_body_material', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.bodymaterial'),
        ),
        migrations.AddField(
            model_name='body',
            name='id_body_type',
            field=models.ForeignKey(db_column='id_body_type', on_delete=django.db.models.deletion.DO_NOTHING, to='guitarStoreApp.bodytype'),
        ),
    ]
